id: P010801
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-20 10:25:09.477108
source_metadata:
  id: bdr:W3CN4869
  title: ཤེར་ཕྱིན་བརྒྱད་སྟོང་པའི་བཤད་པ་མངོན་རྟོགས་རྒྱན་གྱི་སྣང་བ།
  author: ''
  volumes:
    ab004e338eee4ec0a78d31017a18a08a:
      image_group_id: I3CN4871
      title: ''
      volume_number: 1
      total_pages: 621
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
