id: IF623CFCC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T03:35:32+00:00'
last_modified: '2022-06-08T17:37:30.885457+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4869
  title: ཤེར་ཕྱིན་བརྒྱད་སྟོང་པའི་བཤད་པ་མངོན་རྟོགས་རྒྱན་གྱི་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3838':
      image_group_id: I3CN4871
      title: ''
      total_pages: 621
      order: 1
      base_file: 3838.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
